import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import * as cli from '../src/migration/reconcile-cli.mjs';
import { reconciliationPlanDigest } from '../src/migration/reconcile.mjs';
import { resolveCommandCenterDatabasePath } from '../src/metadata/path.mjs';

test('pinned initialization CLI verifies without creating and refuses another resolved state or cancelled authority', async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'metadata-init-cli-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const stateDir = path.join(root, 'state');
  const { mkdir } = await import('node:fs/promises'); await mkdir(stateDir);
  const planPath = path.join(root, 'plan.json');
  const plan = { schemaVersion: 1, purpose: 'command-center-metadata-initialization', stateDirectory: stateDir, metadataSchemaVersion: 8 };
  await writeFile(planPath, JSON.stringify(plan));
  const previous = process.env.OPENCLAW_STATE_DIR; process.env.OPENCLAW_STATE_DIR = stateDir;
  t.after(() => { if (previous === undefined) delete process.env.OPENCLAW_STATE_DIR; else process.env.OPENCLAW_STATE_DIR = previous; });
  const invoke = (mode, extra = {}) => cli.runConfiguredMetadataInitialization({ mode, planPath, expectedDigest: reconciliationPlanDigest(plan), ...extra });
  await assert.rejects(invoke('verify'), { code: 'existing-metadata-required' });
  assert.deepEqual(await readdir(stateDir), []);
  await assert.rejects(invoke('execute', { expectedDigest: '0'.repeat(64) }), { code: 'reconciliation-plan-digest-mismatch' });
  const cancellation = new AbortController(); cancellation.abort(Object.assign(new Error('cancelled'), { code: 'test-cancelled' }));
  await assert.rejects(invoke('execute', { signal: cancellation.signal }), { code: 'test-cancelled' });
  process.env.OPENCLAW_STATE_DIR = root;
  await assert.rejects(invoke('execute'), { code: 'initialization-state-mismatch' });
  process.env.OPENCLAW_STATE_DIR = stateDir;
  assert.deepEqual(await readdir(stateDir), []);
  assert.deepEqual(await invoke('execute'), { phase: 'verified', schemaVersion: 8, disposition: 'created' });
  const bytes = await readFile(resolveCommandCenterDatabasePath(stateDir));
  assert.deepEqual(await invoke('verify'), { phase: 'verified', schemaVersion: 8, disposition: 'existing' });
  assert.deepEqual(await invoke('execute'), { phase: 'verified', schemaVersion: 8, disposition: 'existing' });
  assert.deepEqual(await readFile(resolveCommandCenterDatabasePath(stateDir)), bytes);
});
